name: Update monitoring

on:
  push:
    paths:
      - 'check_resource_usage/VSC_monitoring/input/**.csv'
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Replace 'x' with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r rcheck_resource_usage/equirements.txt  # Replace with your requirements file if needed

      - name: Run Python script
        run: python check_resource_usage/VSC_monitoring/monitoring.py  # Replace 'script.py' with your Python script filename and 'folder' with your folder name

      - name: Update Date
        run: |
          #!/bin/bash
          
          file="README.md"
          current_date=$(date +"%d\/%m\/%Y")
          sed -i "s/Date: [0-9]\{2\}\/[0-9]\{2\}\/[0-9]\{4\}/Date: $current_date/g" "$file"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-updated monitoring.png
